### ISSUE TITLE
Can tagging_converter support consecutive DELETE|add_phrases?

### ISSUE THREAD

**Issue by qiuhuiGithub** [google-research/lasertagger#10]
Hi, in the follow case, I want to change the target into tags, and I suppose the result will be "DELETE|hi--DELETE|hi", but it can't get converted.  
 `
  input_texts, target = ['hello hello .'], 'hi hi .'  # ['hello Tim hello .]', 'hi Tim hi' works fine.

  phrase_vocabulary=['hi']

  task = tagging.EditingTask(input_texts) 

  converter = tagging_converter.TaggingConverter(phrase_vocabulary, True) 

  tags = converter.compute_tags(task, target) 
`
Looking forward to your reply. Thanks.

**Comment by ekQ** [comment]
Hi, indeed tagging_converter doesn't currently support insertions in consecutive DELETEd tokens (see the explanation [here](https://github.com/google-research/lasertagger/blob/master/tagging_converter.py#L105-L116)). Instead you would need to have 'hi hi' in your phrase_vocabulary to be able to convert that example.

**Comment by qiuhuiGithub** [comment]
> Hi, indeed tagging_converter doesn't currently support insertions in consecutive DELETEd tokens (see the explanation [here](https://github.com/google-research/lasertagger/blob/master/tagging_converter.py#L105-L116)). Instead you would need to have 'hi hi' in your phrase_vocabulary to be able to convert that example.

Got it, Thanks.  And will you support this in the future version? Lasertagger can not deal with the case I mention above if 'hi' in phrase_vocabulary but 'hi hi' not.  This may be a limitation.

**Comment by ekQ** [comment]
I agree that in some situations it would be useful to support that. We don't have plans to add that feature in the near future, but I'd be happy to consider a pull request if you want to implement it yourself.

**Comment by qiuhuiGithub** [comment]
> I agree that in some situations it would be useful to support that. We don't have plans to add that feature in the near future, but I'd be happy to consider a pull request if you want to implement it yourself.

Okay, I'll try to implement it myself and test will there be any gain in my tasks. Thanks for your kind reply!

**Comment by ekQ** [comment]
Great, let me know how it goes!
