### ISSUE TITLE
Problem with pkg-resources==0.0.0 when installing requirements.txt

### ISSUE THREAD

**Issue by tranthuykieu** [google-research/lasertagger#17]
I installed the packages using the command line: pip install -r requirements.txt.
Then I got the problem:

ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0
ERROR: No matching distribution found for pkg-resources==0.0.0

Does anyone get it or know to fix it ?
Thanks a lot.

**Comment by ekQ** [comment]
I don't remember getting it, but others seem to have had similar issues: https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command

Could you try removing the line and seeing if you run into other issues?

**Comment by tranthuykieu** [comment]
I removed the line and the implementation works well. Thank you.

**Comment by ekQ** [comment]
Great, thanks for the update.

**Comment by RowlandWanderi** [comment]
Hi , I have the same issue. I've been trying to run pipenv install but I keep getting an error saying
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches importlib-metadata6.0.0
Tried: (no version found at all)

when i pipenv graph i get pkg-resources==0.0.0
can you please guide me how to correct this step by step in the terminal as i am new to using python.
i would appreciate your help

**Comment by ultrawalle** [comment]
您好，我是王磊，您的邮件我已收到，谢谢！

**Comment by Oskar0112** [comment]
Hello I had the same issue.
But i managed to fix it.
There is nowhere pkg-resources==0.0.0 in requirements.txt but error message was occured continuously.
So the solving problem is to give the instruction to the terminal.
pip install --upgrade setuptools pip
This command will be helpful.
it might be due to issues with your Python environment setup or conflicting package installations. I think.
btw, hope your good luck.

**Comment by ultrawalle** [comment]
您好，我是王磊，您的邮件我已收到，谢谢！
