### ISSUE TITLE
 How do tag "keep" and "delete" accurately correspond to the input token ?

### ISSUE THREAD

**Issue by DennyDreamer** [google-research/lasertagger#23]
I created a similar model for text editing, but when the length of the input text is too long, the number of "delete" and "keep" tags output by the decoder is not equal to the input length

**Comment by ekQ** [comment]
If the input has more than `max_seq_length` wordpieces, the input and the label sequence are truncated (https://github.com/google-research/lasertagger/blob/master/bert_example.py#L169-L170).
