### ISSUE TITLE
How to use GPU?

### ISSUE THREAD

**Issue by yashnv** [google-research/lasertagger#4]
How does this use GPU? I see the GPU utility is 0%.

**Comment by ekQ** [comment]
Hi Yash, maybe you tried it already, but if not, you should try uncommenting the following line:
`# tensorflow-gpu==1.14.0  # GPU version of TensorFlow.`
and commenting out the first line of requirements.txt before installing the requirements with pip.
Does this help?

**Comment by yashnv** [comment]
I am using Tensorflow 1.15 where temsorflow is tensorflow-gpu by default.
But I saw 0% GPU utilization in the training step.

**Comment by Dod-o** [comment]
Did you solve this problem? 
I saw 0% GPU utilization, too.

**Comment by yashnv** [comment]
This was pretty much my fault, as the code utilizes GPU by default.

I had a poorly configured tensorflow setup that could not use GPUs. I swiched to Nvidia's Tensorflow-1 19.12 NGC container, which come preconfigured for GPU .
